### PR TITLE
Cleanup specs

### PR DESCRIPTION
**Pull request by ms-ati**

### CODE REVIEW

**Comment by ms-ati** [comment]
@tcrayford did you have a chance to look at this?

Also, great job with the blog post about Riak -- it got circulated at work :clap:

**Comment by tcrayford** [comment]
@ms-ati mind just removing `spec_helper` entirely then? I don't see the point of just having it - there's only one spec file here.

**Comment by ms-ati** [comment]
Ah sure, one sec

**Comment by tcrayford** [comment]
awesome :+1:

**Comment by ms-ati** [comment]
merge?

**Comment by tcrayford** [comment]
yep. Travis was taking aaages, so I stopped watching it.

**Pull request merged**
