### PR TITLE
Add HISTORY.md

### PR DESCRIPTION
**Pull request by ms-ati**
re #25

### CODE REVIEW

**Comment by ms-ati** [comment]
Hi @tcrayford, this is my last PR (creating the HISTORY.md) before discussing how to make a release, which I've presumed might be 1.8.0.

Do you want to discuss here, or shall I open another issue?

**Comment by tcrayford** [comment]
this is fine. I can do the release myself :)

**Comment by ms-ati** [comment]
@tcrayford ok cool. Just a reminder, the tagged release should have HISTORY.md updated and the version in values.gemspec. I don't think there's any other files that need to change for a release, are there?

**Comment by tcrayford** [comment]
nope.

**Pull request merged**
