### PR TITLE
Add MRI, JRuby, and Rubinius versions to test in Travis CI

### PR DESCRIPTION
**Pull request by ms-ati**
Re #25
Re #28

### CODE REVIEW

**Comment by ms-ati** [comment]
A ha! So now we are alerted that `bundle install` fails on 1.8.7: https://travis-ci.org/tcrayford/Values/jobs/68010914

@tcrayford if it's ok with you, I'd rather have you merge this PR which adds the testing, and I'll fix individual version failures in follow on PRs

**Comment by tcrayford** [comment]
@ms-ati I'd rather not ever have a broken commit on master. Please to fix it here and rebase it to one commit (or rebase it so the fix comes before the testing).

**Comment by ms-ati** [comment]
@tcrayford How about we compromise. I can change this PR so that the versions that fail are marked "allow to fail", so that the build is considered passed, but we have the feedback.

My reasoning is that this PR is just adding the CI knowledge. I don't want to comflate that interest with also fixing any version incompatibilities (such as with 1.8.7) that it is simply revealing, rather than causing.

Does that make sense?

**Comment by tcrayford** [comment]
@ms-ati that still means bisect won't work in the future. How about submitting a new PR that fixes this, which I merge first, then I merge this one.

**Comment by ms-ati** [comment]
Oh! Ha that's a good compromise. Ok, I'm on board for pre-PRs to get all the versions working before this is merged, as you suggest.

**Comment by ms-ati** [comment]
@tcrayford Ok to merge, all rubies are green now :)

**Pull request merged**
