### PR TITLE
Add #with method supporting hash args

### PR DESCRIPTION
**Pull request by ms-ati**
The `#copy` method allows you to start with an instance
of a `Value` type, and obtain a new instance by replacing
some or all of the field values.

This is very similar to the `#copy` method of Scala case
classes.

Example:

```ruby
Point = Value.new(:x, :y)
p0 = Point.new(0, 0)
p1 = p0.copy(x: 5) # x as hash arg
p2 = p0.copy(y: 5) # y as hash arg
p3 = p0.copy(5, 5) # both as positional args
```

### CODE REVIEW

**Comment by tcrayford** [comment]
Marc: wanna rename this to `#with` like I suggested? Once that's done I'm happy to merge.

**Comment by ms-ati** [comment]
Hi Tom! Yes, I'll get to this soon and send up an updated PR. Happy "Spring Bank Holiday" / "May Bank Holiday", which I understand corresponds with US Memorial Day Weekend. Cheers.

**Comment by ms-ati** [comment]
Hi Tom. This PR should be ready to review and merge now. I've renamed the method to `#with`, and removed the support for positional args in `#with` because, per discussion, it's not worth the extra complexity. If you prefer, I can squash the two commits in this PR, just let me know.

**Comment by ms-ati** [comment]
Thanks! Very much appreciate it. More to come when I get a chance later this week.

**Pull request merged**
